### ISSUE TITLE
Slack is currently not loading

### ISSUE THREAD

**Issue by akinofftz** [meetfranz/recipe-slack#4]
Slack tries to load, but breaks showing an error message. Everything is fine when using browser.

Console shows some errors:

```
messages:2159 🐶 CDN JS watchdog: No TS or TS.client in page? Possible client / network / CDN failure. May reload in 2500 ms.
rollup-core_required_libs.de-DE.e4fb315….min.js:1 Unhandled rejection TypeError: Cannot read property 'onStart' of undefined
    at e (https://a.slack-edge.com/bv1-1/rollup-core_required_ts.de-DE.ba6746fc34304a68f7c3.min.js:1:94952)
    at e (https://a.slack-edge.com/bv1-1/rollup-core_required_ts.de-DE.ba6746fc34304a68f7c3.min.js:1:90831)
    at l (https://a.slack-edge.com/bv1-1/rollup-core_required_libs.de-DE.e4fb315652e833a85dd4.min.js:1:465655)
    at S._settlePromiseFromHandler (https://a.slack-edge.com/bv1-1/rollup-core_required_libs.de-DE.e4fb315652e833a85dd4.min.js:1:438140)
    at S._settlePromise (https://a.slack-edge.com/bv1-1/rollup-core_required_libs.de-DE.e4fb315652e833a85dd4.min.js:1:438992)
    at S._settlePromiseCtx (https://a.slack-edge.com/bv1-1/rollup-core_required_libs.de-DE.e4fb315652e833a85dd4.min.js:1:439532)
    at l._drainQueue (https://a.slack-edge.com/bv1-1/rollup-core_required_libs.de-DE.e4fb315652e833a85dd4.min.js:1:396715)
    at l._drainQueues (https://a.slack-edge.com/bv1-1/rollup-core_required_libs.de-DE.e4fb315652e833a85dd4.min.js:1:396768)
    at drainQueues (https://a.slack-edge.com/bv1-1/rollup-core_required_libs.de-DE.e4fb315652e833a85dd4.min.js:1:395058)
    at MutationObserver.<anonymous> (https://a.slack-edge.com/bv1-1/rollup-core_required_libs.de-DE.e4fb315652e833a85dd4.min.js:1:455467)
g @ rollup-core_required_libs.de-DE.e4fb315….min.js:1
H @ rollup-core_required_libs.de-DE.e4fb315….min.js:1
q @ rollup-core_required_libs.de-DE.e4fb315….min.js:1
r._notifyUnhandledRejection @ rollup-core_required_libs.de-DE.e4fb315….min.js:1
l._drainQueue @ rollup-core_required_libs.de-DE.e4fb315….min.js:1
l._drainQueues @ rollup-core_required_libs.de-DE.e4fb315….min.js:1
drainQueues @ rollup-core_required_libs.de-DE.e4fb315….min.js:1
(anonymous) @ rollup-core_required_libs.de-DE.e4fb315….min.js:1
plugin.js:33 settings-update Object {activeService: "d0cb3ab5-7c02-4336-b300-97baa7d166ea", appStarts: 34, autoLaunchInBackground: false, autoLaunchOnStart: true, beta: false…}
rollup-core_required_libs.de-DE.e4fb315….min.js:1 Jan-30 14:11:39.825 [T033GDUR4] SOCKET-MANAGER:  Changing from prov_connecting to prov_connected
rollup-core_required_libs.de-DE.e4fb315….min.js:1 Jan-30 14:11:39.827 [T033GDUR4] SOCKET-MANAGER:  will stay in prov_connected state for up to 60000 ms
rollup-core_required_libs.de-DE.e4fb315….min.js:1 Jan-30 14:11:39.829 [INFO] Got start data from Socket Manager; hydrating it
rollup-core_required_ts.de-DE.ba6746f….min.js:1 2018/1/30 14:11:39.836  Received a reply to a message we have no record of sending (reply_to = 16502, type = message)
e @ rollup-core_required_ts.de-DE.ba6746f….min.js:1
e @ rollup-core_required_ts.de-DE.ba6746f….min.js:1
(anonymous) @ rollup-core_required_libs.de-DE.e4fb315….min.js:1
C @ rollup-core_required_libs.de-DE.e4fb315….min.js:1
_socket.onmessage @ rollup-core_required_libs.de-DE.e4fb315….min.js:1
messages:2159 🐶 No TS or !TS.client after 2500 msec - giving up, showing load trouble screen.
warn @ messages:2159
countFailure @ messages:2312
(anonymous) @ messages:2328
messages:2164 🐶 TS and TS.client recovered after inline check failed, loaded within 2500 ms.
webview.js:20 Uncaught TypeError: Cannot read property 'remove' of null
    at setTimeout (webview.js:20)
setTimeout @ webview.js:20
webview.js:20 Uncaught TypeError: Cannot read property 'remove' of null
    at setTimeout (webview.js:20)
setTimeout @ webview.js:20
webview.js:20 Uncaught TypeError: Cannot read property 'remove' of null
    at setTimeout (webview.js:20)
setTimeout @ webview.js:20
webview.js:20 Uncaught TypeError: Cannot read property 'remove' of null
    at setTimeout (webview.js:20)
setTimeout @ webview.js:20
rollup-core_required_libs.de-DE.e4fb315….min.js:1 Jan-30 14:12:39.831 [T033GDUR4] SOCKET-MANAGER:  Spent 60000 ms in prov_connected state; giving up
rollup-core_required_libs.de-DE.e4fb315….min.js:1 Jan-30 14:12:39.831 [T033GDUR4] SOCKET-MANAGER:  Changing from prov_connected to error
rollup-core_required_libs.de-DE.e4fb315….min.js:1 Jan-30 14:12:39.832 [T033GDUR4] SOCKET-MANAGER:  will stay in error state for up to 10000 ms
rollup-core_required_libs.de-DE.e4fb315….min.js:1 Jan-30 14:12:39.834 T033GDUR4 SOCKET-MANAGER:  Closing socket due to unknown error
k @ rollup-core_required_libs.de-DE.e4fb315….min.js:1
w @ rollup-core_required_libs.de-DE.e4fb315….min.js:1
(anonymous) @ rollup-core_required_libs.de-DE.e4fb315….min.js:1
(anonymous) @ rollup-core_required_libs.de-DE.e4fb315….min.js:1
(anonymous) @ rollup-core_required_libs.de-DE.e4fb315….min.js:1
(anonymous) @ rollup-core_required_libs.de-DE.e4fb315….min.js:1
(anonymous) @ application.de-DE.08626ab….min.js:1
(anonymous) @ rollup-core_required_libs.de-DE.e4fb315….min.js:1
(anonymous) @ application.de-DE.08626ab….min.js:1
e @ modern.vendor.de-DE.95fa98d….min.js:1
(anonymous) @ rollup-core_required_libs.de-DE.e4fb315….min.js:1
(anonymous) @ application.de-DE.08626ab….min.js:1
l @ rollup-core_required_libs.de-DE.e4fb315….min.js:1
e @ rollup-core_required_libs.de-DE.e4fb315….min.js:1
e @ rollup-core_required_libs.de-DE.e4fb315….min.js:1
e @ rollup-core_required_libs.de-DE.e4fb315….min.js:1
e @ rollup-core_required_libs.de-DE.e4fb315….min.js:1
(anonymous) @ rollup-core_required_libs.de-DE.e4fb315….min.js:1
rollup-core_required_ts.de-DE.ba6746f….min.js:1 2018/1/30 14:12:39.835  Stacktrace: ↴
 at e (https://a.slack-edge.com/bv1-1/rollup-core_required_ts.de-DE.ba6746fc34304a68f7c3.min.js:1:68470)
at https://a.slack-edge.com/bv1-1/rollup-core_required_libs.de-DE.e4fb315652e833a85dd4.min.js:1:1511243
at e (https://a.slack-edge.com/bv1-1/rollup-core_required_libs.de-DE.e4fb315652e833a85dd4.min.js:1:1662642)
at e (https://a.slack-edge.com/bv1-1/rollup-core_required_libs.de-DE.e4fb315652e833a85dd4.min.js:1:1664365)
at https://a.slack-edge.com/bv1-1/rollup-core_required_libs.de-DE.e4fb315652e833a85dd4.min.js:1:1666650
rollup-core_required_libs.de-DE.e4fb315….min.js:1 Jan-30 14:12:39.837 [T033GDUR4] SOCKET-MANAGER:  Changing from error to wait_for_connectivity
rollup-core_required_libs.de-DE.e4fb315….min.js:1 Jan-30 14:12:39.837 [T033GDUR4] SOCKET-MANAGER:  will stay in wait_for_connectivity state for up to 300000 ms
rollup-core_required_libs.de-DE.e4fb315….min.js:1 Jan-30 14:12:40.227 [T033GDUR4] SOCKET-MANAGER:  Changing from wait_for_connectivity to wait_for_rate_limit
rollup-core_required_libs.de-DE.e4fb315….min.js:1 Jan-30 14:12:40.227 [T033GDUR4] SOCKET-MANAGER:  will stay in wait_for_rate_limit state for up to 120000 ms
rollup-core_required_libs.de-DE.e4fb315….min.js:1 Jan-30 14:12:40.229 [T033GDUR4] SOCKET-MANAGER:  Changing from wait_for_rate_limit to connect
rollup-core_required_libs.de-DE.e4fb315….min.js:1 Jan-30 14:12:40.230 [T033GDUR4] SOCKET-MANAGER:  will stay in connect state for up to 10000 ms
rollup-core_required_libs.de-DE.e4fb315….min.js:1 Jan-30 14:12:40.231 [T033GDUR4] SOCKET-MANAGER:  Changing from connect to checking_fast_reconnect
rollup-core_required_libs.de-DE.e4fb315….min.js:1 Jan-30 14:12:40.232 [T033GDUR4] SOCKET-MANAGER:  will stay in checking_fast_reconnect state for up to 60000 ms
rollup-core_required_libs.de-DE.e4fb315….min.js:1 Jan-30 14:12:40.233 [T033GDUR4] SOCKET-MANAGER:  Changing from checking_fast_reconnect to prov_connect
rollup-core_required_libs.de-DE.e4fb315….min.js:1 Jan-30 14:12:40.234 [T033GDUR4] SOCKET-MANAGER:  will stay in prov_connect state for up to 10000 ms
rollup-core_required_libs.de-DE.e4fb315….min.js:1 Jan-30 14:12:40.234 [T033GDUR4] SOCKET-MANAGER:  Changing from prov_connect to prov_connecting
rollup-core_required_libs.de-DE.e4fb315….min.js:1 Jan-30 14:12:40.235 [T033GDUR4] SOCKET-MANAGER:  will stay in prov_connecting state for up to 20000 ms
rollup-core_required_libs.de-DE.e4fb315….min.js:1 Jan-30 14:12:40.801 [T033GDUR4] SOCKET-MANAGER:  Changing from prov_connecting to prov_connected
rollup-core_required_libs.de-DE.e4fb315….min.js:1 Jan-30 14:12:40.803 [T033GDUR4] SOCKET-MANAGER:  will stay in prov_connected state for up to 60000 ms
rollup-core_required_ts.de-DE.ba6746f….min.js:1 2018/1/30 14:12:40.831  Received a reply to a message we have no record of sending (reply_to = 16502, type = message)
```

**Comment by akinofftz** [comment]
Okay, manually removed all cache files and now it works again.

**Comment by henrebotha** [comment]
I'm getting very similar issues as of this morning and struggling to resolve it. 

Console:

```
rollup-core_required_libs.76c57d7….min.js:1 Uncaught SyntaxError: Invalid or unexpected token
webpack.manifest.d67948d….min.js:1 Uncaught TypeError: Cannot read property 'call' of undefined
    at r (webpack.manifest.d67948d….min.js:1)
    at Object.<anonymous> (application.5b92cf7….min.js:1)
    at r (webpack.manifest.d67948d….min.js:1)
    at Object.<anonymous> (application.5b92cf7….min.js:1)
    at r (webpack.manifest.d67948d….min.js:1)
    at c (webpack.manifest.d67948d….min.js:1)
    at application.5b92cf7….min.js:1
r @ webpack.manifest.d67948d….min.js:1
(anonymous) @ application.5b92cf7….min.js:1
r @ webpack.manifest.d67948d….min.js:1
(anonymous) @ application.5b92cf7….min.js:1
r @ webpack.manifest.d67948d….min.js:1
c @ webpack.manifest.d67948d….min.js:1
(anonymous) @ application.5b92cf7….min.js:1
rollup-core_required_ts.bfca43d….min.js:1 TSM.interop not found, app almost certainly will not boot properly
(anonymous) @ rollup-core_required_ts.bfca43d….min.js:1
11176 @ rollup-core_required_ts.bfca43d….min.js:1
r @ webpack.manifest.d67948d….min.js:1
11174 @ rollup-core_required_ts.bfca43d….min.js:1
r @ webpack.manifest.d67948d….min.js:1
c @ webpack.manifest.d67948d….min.js:1
(anonymous) @ rollup-core_required_ts.bfca43d….min.js:1
rollup-core_required_ts.bfca43d….min.js:1 Uncaught ReferenceError: _ is not defined
    at rollup-core_required_ts.bfca43d….min.js:1
    at Object.11176 (rollup-core_required_ts.bfca43d….min.js:1)
    at r (webpack.manifest.d67948d….min.js:1)
    at Object.11174 (rollup-core_required_ts.bfca43d….min.js:1)
    at r (webpack.manifest.d67948d….min.js:1)
    at c (webpack.manifest.d67948d….min.js:1)
    at rollup-core_required_ts.bfca43d….min.js:1
(anonymous) @ rollup-core_required_ts.bfca43d….min.js:1
11176 @ rollup-core_required_ts.bfca43d….min.js:1
r @ webpack.manifest.d67948d….min.js:1
11174 @ rollup-core_required_ts.bfca43d….min.js:1
r @ webpack.manifest.d67948d….min.js:1
c @ webpack.manifest.d67948d….min.js:1
(anonymous) @ rollup-core_required_ts.bfca43d….min.js:1
bootstrap-client.e486222….min.js:1 Uncaught TypeError: t is not a function
    at bootstrap-client.e486222….min.js:1
    at Object.1797 (bootstrap-client.e486222….min.js:1)
    at r (webpack.manifest.d67948d….min.js:1)
    at c (webpack.manifest.d67948d….min.js:1)
    at bootstrap-client.e486222….min.js:1
(anonymous) @ bootstrap-client.e486222….min.js:1
1797 @ bootstrap-client.e486222….min.js:1
r @ webpack.manifest.d67948d….min.js:1
c @ webpack.manifest.d67948d….min.js:1
(anonymous) @ bootstrap-client.e486222….min.js:1
rollup-core_required_ts.bfca43d….min.js:1 Uncaught TypeError: L is not a function
    at Object.e [as boot] (rollup-core_required_ts.bfca43d….min.js:1)
    at messages:2163
e @ rollup-core_required_ts.bfca43d….min.js:1
(anonymous) @ messages:2163
rollup-secondary_a_required.c0215fd….min.js:1 Uncaught ReferenceError: signals is not defined
    at rollup-secondary_a_required.c0215fd….min.js:1
    at Object.11187 (rollup-secondary_a_required.c0215fd….min.js:1)
    at r (webpack.manifest.d67948d….min.js:1)
    at Object.11186 (rollup-secondary_a_required.c0215fd….min.js:1)
    at r (webpack.manifest.d67948d….min.js:1)
    at c (webpack.manifest.d67948d….min.js:1)
    at rollup-secondary_a_required.c0215fd….min.js:1
(anonymous) @ rollup-secondary_a_required.c0215fd….min.js:1
11187 @ rollup-secondary_a_required.c0215fd….min.js:1
r @ webpack.manifest.d67948d….min.js:1
11186 @ rollup-secondary_a_required.c0215fd….min.js:1
r @ webpack.manifest.d67948d….min.js:1
c @ webpack.manifest.d67948d….min.js:1
(anonymous) @ rollup-secondary_a_required.c0215fd….min.js:1
rollup-core_required_ts.bfca43d….min.js:1 Uncaught TypeError: G is not a function
    at Object.e [as registerModule] (rollup-core_required_ts.bfca43d….min.js:1)
    at rollup-secondary_b_required.ae6df2c….min.js:1
    at Object.11297 (rollup-secondary_b_required.ae6df2c….min.js:1)
    at r (webpack.manifest.d67948d….min.js:1)
    at Object.11296 (rollup-secondary_b_required.ae6df2c….min.js:1)
    at r (webpack.manifest.d67948d….min.js:1)
    at c (webpack.manifest.d67948d….min.js:1)
    at rollup-secondary_b_required.ae6df2c….min.js:1
e @ rollup-core_required_ts.bfca43d….min.js:1
(anonymous) @ rollup-secondary_b_required.ae6df2c….min.js:1
11297 @ rollup-secondary_b_required.ae6df2c….min.js:1
r @ webpack.manifest.d67948d….min.js:1
11296 @ rollup-secondary_b_required.ae6df2c….min.js:1
r @ webpack.manifest.d67948d….min.js:1
c @ webpack.manifest.d67948d….min.js:1
(anonymous) @ rollup-secondary_b_required.ae6df2c….min.js:1
rollup-client.dd19ec8….min.js:1 Uncaught ReferenceError: signals is not defined
    at rollup-client.dd19ec8….min.js:1
    at Object.11357 (rollup-client.dd19ec8….min.js:1)
    at r (webpack.manifest.d67948d….min.js:1)
    at Object.11356 (rollup-client.dd19ec8….min.js:1)
    at r (webpack.manifest.d67948d….min.js:1)
    at c (webpack.manifest.d67948d….min.js:1)
    at rollup-client.dd19ec8….min.js:1
(anonymous) @ rollup-client.dd19ec8….min.js:1
11357 @ rollup-client.dd19ec8….min.js:1
r @ webpack.manifest.d67948d….min.js:1
11356 @ rollup-client.dd19ec8….min.js:1
r @ webpack.manifest.d67948d….min.js:1
c @ webpack.manifest.d67948d….min.js:1
(anonymous) @ rollup-client.dd19ec8….min.js:1
messages:2208 🐶 CDN JS watchdog: No TS or TS.client in page? Possible client / network / CDN failure. May reload in 2500 ms.
warn @ messages:2208
checkJS @ messages:2374
(anonymous) @ messages:2399
(anonymous) @ messages:2404
plugin.js:33 settings-update Object {activeService: "5861282f-60fb-49a8-b33e-47e679588376", appStarts: 268, autoLaunchInBackground: false, autoLaunchOnStart: true, beta: true…}
messages:2208 🐶 No TS or !TS.client after 2500 msec - giving up, showing load trouble screen.
warn @ messages:2208
countFailure @ messages:2361
(anonymous) @ messages:2377
messages:2213 🐶 TS and TS.client recovered after inline check failed, loaded within 2500 ms.
plugin.js:33 settings-update Object {activeService: "5861282f-60fb-49a8-b33e-47e679588376", appStarts: 268, autoLaunchInBackground: false, autoLaunchOnStart: true, beta: true…}
webview.js:20 Uncaught TypeError: Cannot read property 'remove' of null
    at setTimeout (webview.js:20)
setTimeout @ webview.js:20
webview.js:20 Uncaught TypeError: Cannot read property 'remove' of null
    at setTimeout (webview.js:20)
setTimeout @ webview.js:20
webview.js:20 Uncaught TypeError: Cannot read property 'remove' of null
    at setTimeout (webview.js:20)
setTimeout @ webview.js:20
plugin.js:33 settings-update Object {activeService: "5861282f-60fb-49a8-b33e-47e679588376", appStarts: 268, autoLaunchInBackground: false, autoLaunchOnStart: true, beta: true…}
webview.js:20 Uncaught TypeError: Cannot read property 'remove' of null
    at setTimeout (webview.js:20)
setTimeout @ webview.js:20
plugin.js:33 settings-update Object {activeService: "5861282f-60fb-49a8-b33e-47e679588376", appStarts: 268, autoLaunchInBackground: false, autoLaunchOnStart: true, beta: true…}
plugin.js:33 settings-update Object {activeService: "5861282f-60fb-49a8-b33e-47e679588376", appStarts: 268, autoLaunchInBackground: false, autoLaunchOnStart: true, beta: true…}
plugin.js:33 settings-update Object {activeService: "5861282f-60fb-49a8-b33e-47e679588376", appStarts: 268, autoLaunchInBackground: false, autoLaunchOnStart: true, beta: true…}
plugin.js:33 settings-update Object {activeService: "5861282f-60fb-49a8-b33e-47e679588376", appStarts: 268, autoLaunchInBackground: false, autoLaunchOnStart: true, beta: true…}
plugin.js:33 settings-update Object {activeService: "5861282f-60fb-49a8-b33e-47e679588376", appStarts: 268, autoLaunchInBackground: false, autoLaunchOnStart: true, beta: true…}
```

This is on macOS 10.13.3 running Franz 5.0.0-beta.16.762. Neither macOS nor Franz has updated in the last 24 hours, so it's not a version-specific thing.
